import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import SessionWrapper from "./Components/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionWrapper>
          <div className="relative min-h-screen w-full bg-slate-950 overflow-hidden">
            {/* Background effects should be behind everything */}
            <div className="pointer-events-none absolute z-0 bottom-0 left-[-20%] top-[-10%] h-[500px] w-[500px] rounded-full bg-[radial-gradient(circle_farthest-side,rgba(255,0,182,.15),rgba(255,255,255,0))]" />
            <div className="pointer-events-none absolute z-0 bottom-0 right-[-20%] top-[-10%] h-[500px] w-[500px] rounded-full bg-[radial-gradient(circle_farthest-side,rgba(0,123,255,.15),rgba(255,255,255,0))]" />

            {/* Foreground content should be above */}
            <div className="relative z-10">
              {children}
              <Navbar />
            </div>
          </div>
        </SessionWrapper>
      </body>
    </html>
  );
}
